version: '3'

services:
  tensorflow:
    # https://hub.docker.com/r/tensorflow/tensorflow
    build: 
      dockerfile: ./research/object_detection/dockerfiles/tf2/Dockerfile
      context: ./tensorflow-models/.
    # image: tensorflow/tensorflow